contacts:
  name: Connor Fitzgerald
  title: Graphics Engineer
  email: connorwadefitzgerald@gmail.com
  address: "New York City, NY"
  linkedin:
    url: https://www.linkedin.com/in/cwfitz/
    displayText: cwfitz
  github:
    url: https://github.com/cwfitzgerald/
    displayText: "@cwfitzgerald"
  website:
    url: https://cwfitz.com
    displayText: cwfitz.com

position: Graphics Engineer

# This is the date the content was last updated, not the date the resume was generated.
content_last_updated: "March 2025"

jobs:
  - position: Graphics Engineer
    company:
      name: Mozilla
      link: https://www.mozilla.org/
    product:
      name: Firefox (WebGPU)
      link: https://firefox.com
    contract: true
    description:
      - Solved critical bugs blocking shipping WebGPU on Windows.
      - Implemented f16 support, allowing many AI workloads to run.
      - Rewrote DX12 sampler descriptor management to resolve complex architectural issue preventing many applications from functioning.
      - Triaged and resolved high-priority GitHub issues as part of ongoing open source maintainership.
      - Reviewed contributions from internal and external contributors, keeping the community active.
    from: "Dec 2024"
    to: "Apr 2025"

  - position: Rendering Engineer
    company:
      name: Let Eyes Equals Two
      link: "https://github.com/leetvr"
    product:
      name: Minecraft Clone & UGC Browser Game
      link: ""
    contract: true
    description:
      - Fixed, debugged, and optimized Rust/Vulkan renderer within a Minecraft-compatible game client.
      - Upgraded shader infrastructure, porting GLSL shaders to the Slang shading language, filing key bugs upstream.
      - Used ECS patterns to make modular and scalable game code.
      - Helped ship a User Generated Content game platform prototype in 12 working days as part of a four-person team.
        Implemented graphics features like skyboxes, ambient occlusion, lighting, and shadows in WebGL2.
    from: "Sep 2024"
    to: "Nov 2024"

  - position: Graphics Engineer
    company:
      name: Modyfi Inc.
      link: https://www.modyfi.com/
    product:
      name: Modyfi
      link: https://www.modyfi.com/
    contract: false
    description:
      - Built and shipped core infrastructure for a realtime non-destructive image manipulation program that runs in the browser.
      - Designed system for generating ergonomic Typescript/React bindings for a Rust/WebAssembly library.
      - Took ownership over large system refactors to work around platform limitations.
      - Built multiple testing solutions to ensure pixel-perfect accuracy when running on actual gpus.
      - Managed Rust tooling and Rust/Typescript integration.
    from: "Jun 2022"
    to: "Sep 2024"
    location: Remote

  - position: Graphics Engineer
    company:
      name: Sophya Inc
      link: "https://sowork.com/"
    product:
      name: SoWork
      link: "https://sowork.com/"
    contract: false
    description:
      - Designed and architected a ECS-based Rust/WebAssembly game engine to replace off-the-shelf Javascript game engine.
      - Supported up to 250 concurrent users in a single room.
      - Built asynchronous, seamless asset loading system.
      - Designed data flows for low-overhead communication between game engine, game server, and database.
    from: "Jan 2021"
    to: "May 2022"
    tags:
      - Game Development
      - Unity
      - C#
    location: Remote

open_source:
  - project: wgpu
    github: gfx-rs/wgpu
    position: Lead Maintainer
    from: "Jun 2020"
    to: "Present"
    description:
      - Developed a robust GPU testing framework to ensure correctness and stability across hardware vendors and operating systems.
      - Built highly optimized resource state tracking infrastructure, resulting in performance improvements of up to 14x.
      - Maintain CI that runs our test suite on every GPU API.
      - Built infrastructure for supporting API extensions.
      - Implemented support for bindless textures.
      - Continued repository maintenance and process improvements.
  - project: rend3
    github: BVE-Reborn/rend3
    position: Creator
    from: "Sep 2020"
    to: "May 2024"
    description:
      - Implemented modular and composible rendergraph.
      - Used Hi-Z occlusion culling, indirect draws, and descriptor indexing to optimize high-poly scenes.
      - Balanced ease of use, performance, and customizability.
      - Upstreamed many improvements into wgpu.

education:
  - place:
      name: Hunter College
      link: "https://hunter.cuny.edu/"
    degree: "B.A."
    major: Computer Science
    from: "2017"
    to: "2021"
    location: New York City, USA

memberships:
  - name: "Invited Expert"
    org: "W3C WebGPU Working Group"
    link: "https://www.w3.org/groups/wg/gpu/participants/#participants"
    description: Worked alongside Google, Apple, Microsoft, and more to shape the WebGPU specification to be easy to use, powerful, and implementable. Brought my experience from building wgpu to improve the specification.

skills:
  - Rust
  - C++
  - Python
  - WebAssembly (wasm)
  - Vulkan
  - D3D12
  - D3D11
  - Metal
  - OpenGL
  - WebGL2
  - WebGPU
  - WGSL
  - HLSL
  - Slang
  - GLSL
  - ECS
  - Markdown

tools:
  - GitHub
  - Visual Studio
  - VSCode
  - git
  - NSight
  - Radeon GPU Profiler
  - Tracy
  - Renderdoc
  - PIX
  - Slack
  - Teams
  - Notion
  - HackMD
