contacts:
  name: Daniel McNab
  title: TODO
  email: TODO
  address: "Yorkshire, England"
  linkedin:
    url: https://www.linkedin.com/in/TBD
    displayText: TBD
  github:
    url: https://github.com/DJMcNab/
    displayText: "@DJMcNab"
  website:
    # TODO.
    url: https://djmcnab.com
    displayText: djmcnab.com

position: TODO

# This is the date the content was last updated, not the date the resume was generated.
content_last_updated: "July 2025"

jobs:
  - position: User Interface/Graphics Researcher
    company:
      name: Google
      link: https://www.google.com/
    product:
      name: Xilem
      link: https://github.com/linebender/xilem
    contract: true
    description:
      - TODO
    from: "February 2024"
    to: "Present"
    location: Remote

  - position: Web Developer
    company:
      name: PwC UK
      link: "https://pwc.co.uk"
    product:
      name: ""
      link: ""
    contract: false
    description:
      - TODO
    from: "August 2023"
    to: "January 2024"
    location: Hybrid

  - position: Degree Apprentice
    company:
      name: PwC UK
      link: https://www.pwc.co.uk
    product:
      name: ""
      link: ""
    contract: false
    description:
      - TODO
    from: "September 2019"
    to: "August 2023"
    location: Hybrid

open_source:
  - project: Xilem
    github: linebender/xilem
    position: Core Maintainer
    from: "March 2024"
    to: "Present"
    description:
      - TODO
  - project: Bevy
    github: bevyengine/bevy
    position: Contributor
    from: "August 2020"
    to: "July 2022"
    description:
      - TODO

education:
  - place:
      name: University of Leeds
      link: "https://www.leeds.ac.uk/"
    degree: "BSc"
    major: Computer Science (Digital & Technology Solutions)
    from: "2019"
    to: "2023"
    location: Leeds, England

memberships: []
#   - name: "Invited Expert"
#     org: "Linebender"
#     link: "https://www.w3.org/groups/wg/gpu/participants/#participants"
#     description: Worked alongside Google, Apple, Microsoft, and more to shape the WebGPU specification to be easy to use, powerful, and implementable. Brought my experience from building wgpu to improve the specification.

skills:
  - Rust
  - WebAssembly (wasm)
  - Vulkan
  - WebGPU
  - WGSL
  - TypeScript
  - WebGL2
  # - ECS
  - Markdown

tools:
  - GitHub
  - Visual Studio
  - VSCode
  - git
  # - NSight
  # - Radeon GPU Profiler
  - Tracy
  - Renderdoc
  # - PIX
  # - Slack
  # - Teams
  # - Notion
  # - HackMD
